#!/usr/bin/env bash
# ==============================================================
# GitHub Auto-Pilot: Bootstrap a New Repo with Full Setup
# Usage: ./bootstrap-new-repo.sh <repo-name> [description]
# ==============================================================

set -euo pipefail

REPO_NAME="${1:?Error: Provide a repo name}"
DESCRIPTION="${2:-Auto-generated by GitHub Auto-Pilot}"
TOKEN="${GITHUB_PERSONAL_ACCESS_TOKEN:-$(grep GITHUB_PERSONAL_ACCESS_TOKEN /root/Projects/Trading-System/.env 2>/dev/null | cut -d= -f2)}"

echo "🚀 GitHub Auto-Pilot Bootstrap"
echo "================================"
echo "Repo: $REPO_NAME"
echo "Desc: $DESCRIPTION"
echo ""

# Step 1: Create repo on GitHub
echo "📦 Creating repository '$REPO_NAME'..."
gh repo create "$REPO_NAME" --public --description "$DESCRIPTION" --clone 2>&1 || {
  echo "❌ Failed to create repo. Check your token permissions."
  exit 1
}

cd "$REPO_NAME"

# Step 2: Add CI/CD workflows
echo "🏗️  Adding CI/CD pipelines..."
mkdir -p .github/workflows

cat > .github/workflows/ci.yml << 'CIEOF'
name: CI
on: [push, pull_request]
jobs:
  ci:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install ruff pytest
      - run: ruff check .
      - run: pytest || echo "No tests yet"
CIEOF

cat > .github/workflows/auto-fix.yml << 'FIXEOF'
name: Auto-Fix
on: [push, pull_request]
permissions:
  contents: write
jobs:
  fix:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.12'
      - run: pip install ruff black
      - run: ruff check . --fix --exit-zero
      - uses: stefanzweifel/git-auto-commit-action@v5
        with:
          commit_message: "🤖 auto-fix"
FIXEOF

# Step 3: Add issue/PR templates
echo "📝 Adding templates..."
mkdir -p .github/ISSUE_TEMPLATE

cat > .github/ISSUE_TEMPLATE/bug_report.md << 'BUGEOF'
---
name: Bug report
about: Report a bug
title: '[BUG] '
labels: bug
---
**Describe the bug**
**To Reproduce**
**Expected behavior**
BUGEOF

cat > .github/ISSUE_TEMPLATE/feature_request.md << 'FEATEOF'
---
name: Feature request
about: Suggest an idea
title: '[FEATURE] '
labels: enhancement
---
**Problem**
**Solution**
FEATEOF

cat > .github/PULL_REQUEST_TEMPLATE.md << 'PREOF'
## Description
Fixes #
## Type
- [ ] Bug fix
- [ ] New feature
PREOF

# Step 4: Add dependabot
echo "🤖 Adding Dependabot..."
cat > .github/dependabot.yml << 'DEPEOF'
version: 2
updates:
  - package-ecosystem: "pip"
    directory: "/"
    schedule:
      interval: "weekly"
DEPEOF

# Step 5: Add standard files
echo "📄 Creating README..."
cat > README.md << 'READEOF'
# $REPO_NAME

$DESCRIPTION

## Quick Start
```bash
pip install -r requirements.txt
python main.py
```
READEOF

echo "# Changelog" > CHANGELOG.md
echo "" > requirements.txt
echo "node_modules/" > .gitignore
echo "__pycache__/" >> .gitignore
echo ".env" >> .gitignore

# Step 6: Initial commit & push
echo "📤 Pushing to GitHub..."
git add .
git commit -m "🎉 Initial setup by GitHub Auto-Pilot"
git push origin main

echo ""
echo "✅ Done! Repo created: https://github.com/vishalm111266-beep/$REPO_NAME"
echo ""
echo "What to do next:"
echo "  1. cd $REPO_NAME"
echo "  2. Start coding!"
echo "  3. Ask opencode: 'github-autopilot, add features to $REPO_NAME'"
